add missing include for std::cerr
fix in ros buildfarm:
```cpp
[ 64%] Building CXX object CMakeFiles/linear_feedback_controller.dir/src/linear_feedback_controller.cpp.o
/usr/lib/ccache/c++ -DBOOST_FUSION_INVOKE_MAX_ARITY=12 -DBOOST_MPL_CFG_NO_PREPROCESSED_HEADERS -DBOOST_MPL_LIMIT_LIST_SIZE=30 -DBOOST_MPL_LIMIT_VECTOR_SIZE=30 -DCOAL_HAS_OCTOMAP -DCOAL_HAVE_OCTOMAP -DCONTROLLER_INTERFACE_MAJOR_VERSION=6 -DCONTROLLER_INTERFACE_MINOR_VERSION=8 -DCONTROLLER_INTERFACE_PATCH_VERSION=0 -DDEFAULT_RMW_IMPLEMENTATION=rmw_fastrtps_cpp -DFASTCDR_DYN_LINK -DFMT_SHARED -DLINEAR_FEEDBACK_CONTROLLER_DO_EXPORT -DLINEAR_FEEDBACK_CONTROLLER_IS_SHARED -DOCTOMAP_MAJOR_VERSION=1 -DOCTOMAP_MINOR_VERSION=10 -DOCTOMAP_PATCH_VERSION=0 -DPINOCCHIO_ENABLE_TEMPLATE_INSTANTIATION -DPINOCCHIO_URDFDOM_HEADERS_MAJOR_VERSION=3 -DPINOCCHIO_URDFDOM_HEADERS_MINOR_VERSION=0 -DPINOCCHIO_URDFDOM_HEADERS_PATCH_VERSION=0 -DPINOCCHIO_WITH_COLLISION -DPINOCCHIO_WITH_HPP_FCL -DPINOCCHIO_WITH_URDFDOM -DROS_PACKAGE_NAME=\"linear_feedback_controller\" -DTINYXML2_IMPORT -D_FILE_OFFSET_BITS=64 -D__STDC_WANT_LIB_EXT1__=1 -Dlinear_feedback_controller_EXPORTS -I/tmp/binarydeb/ros-rolling-linear-feedback-controller-4.0.3/.obj-x86_64-linux-gnu -I/tmp/binarydeb/ros-rolling-linear-feedback-controller-4.0.3/.obj-x86_64-linux-gnu/include -I/tmp/binarydeb/ros-rolling-linear-feedback-controller-4.0.3/include -isystem /opt/ros/rolling/include -isystem /opt/ros/rolling/include/pal_statistics_msgs -isystem /opt/ros/rolling/include/rclcpp -isystem /opt/ros/rolling/include/rclcpp_lifecycle -isystem /opt/ros/rolling/include/pal_statistics -isystem /opt/ros/rolling/include/rcl -isystem /opt/ros/rolling/include/rcl_interfaces -isystem /opt/ros/rolling/include/builtin_interfaces -isystem /opt/ros/rolling/include/rosidl_runtime_c -isystem /opt/ros/rolling/include/rcutils -isystem /opt/ros/rolling/include/rosidl_buffer -isystem /opt/ros/rolling/include/rosidl_typesupport_interface -isystem /opt/ros/rolling/include/service_msgs -isystem /opt/ros/rolling/includefastcdr -isystem /opt/ros/rolling/include/rosidl_runtime_cpp -isystem /opt/ros/rolling/include/rosidl_typesupport_fastrtps_cpp -isystem /opt/ros/rolling/include/rosidl_buffer_backend -isystem /opt/ros/rolling/include/rmw -isystem /opt/ros/rolling/include/rosidl_dynamic_typesupport -isystem /opt/ros/rolling/include/rosidl_typesupport_fastrtps_c -isystem /opt/ros/rolling/include/rosidl_typesupport_introspection_c -isystem /opt/ros/rolling/include/rosidl_typesupport_introspection_cpp -isystem /opt/ros/rolling/include/rcl_logging_interface -isystem /opt/ros/rolling/include/rcl_yaml_param_parser -isystem /opt/ros/rolling/include/type_description_interfaces -isystem /opt/ros/rolling/include/libstatistics_collector -isystem /opt/ros/rolling/include/rcpputils -isystem /opt/ros/rolling/include/statistics_msgs -isystem /opt/ros/rolling/include/rosgraph_msgs -isystem /opt/ros/rolling/include/rosidl_typesupport_cpp -isystem /opt/ros/rolling/include/rosidl_typesupport_c -isystem /opt/ros/rolling/include/tracetools -isystem /opt/ros/rolling/include/lifecycle_msgs -isystem /opt/ros/rolling/include/rcl_lifecycle -isystem /opt/ros/rolling/include/controller_interface -isystem /opt/ros/rolling/include/hardware_interface -isystem /opt/ros/rolling/include/pluginlib -isystem /opt/ros/rolling/include/ament_index_cpp -isystem /opt/ros/rolling/include/class_loader -isystem /opt/ros/rolling/include/urdf -isystem /opt/ros/rolling/include/urdfdom -isystem /opt/ros/rolling/include/urdfdom_headers -isystem /opt/ros/rolling/include/realtime_tools -isystem /opt/ros/rolling/include/rclcpp_action -isystem /opt/ros/rolling/include/action_msgs -isystem /opt/ros/rolling/include/unique_identifier_msgs -isystem /opt/ros/rolling/include/rcl_action -isystem /opt/ros/rolling/include/joint_limits -isystem /opt/ros/rolling/include/trajectory_msgs -isystem /opt/ros/rolling/include/geometry_msgs -isystem /opt/ros/rolling/include/std_msgs -isystem /opt/ros/rolling/include/control_msgs -isystem /opt/ros/rolling/include/diagnostic_msgs -isystem /opt/ros/rolling/include/sensor_msgs -isystem /opt/ros/rolling/include/control_toolbox -isystem /opt/ros/rolling/include/rsl -isystem /usr/include/eigen3 -isystem /usr/share -isystem /opt/ros/rolling/include/filters -isystem /opt/ros/rolling/include/tf2_geometry_msgs -isystem /opt/ros/rolling/include/tf2 -isystem /opt/ros/rolling/include/tf2_ros -isystem /opt/ros/rolling/include/message_filters -isystem /opt/ros/rolling/include/tf2_msgs -isystem /opt/ros/rolling/include/nav_msgs -isystem /opt/ros/rolling/include/linear_feedback_controller_msgs -isystem /opt/ros/rolling/include/tf2_eigen -isystem /opt/ros/rolling/include/pinocchio/deprecated -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion -g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/tmp/binarydeb/ros-rolling-linear-feedback-controller-4.0.3=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fdebug-prefix-map=/tmp/binarydeb/ros-rolling-linear-feedback-controller-4.0.3=/usr/src/ros-rolling-linear-feedback-controller-4.0.3-1resolute.20260728.200827 -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=3 -std=gnu++20 -fPIC -fvisibility=hidden -MD -MT CMakeFiles/linear_feedback_controller.dir/src/linear_feedback_controller.cpp.o -MF CMakeFiles/linear_feedback_controller.dir/src/linear_feedback_controller.cpp.o.d -o CMakeFiles/linear_feedback_controller.dir/src/linear_feedback_controller.cpp.o -c /tmp/binarydeb/ros-rolling-linear-feedback-controller-4.0.3/src/linear_feedback_controller.cpp
/tmp/binarydeb/ros-rolling-linear-feedback-controller-4.0.3/src/linear_feedback_controller.cpp: In member function ‘bool linear_feedback_controller::LinearFeedbackController::set_initial_state(const Eigen::VectorXd&, const Eigen::VectorXd&)’:
/tmp/binarydeb/ros-rolling-linear-feedback-controller-4.0.3/src/linear_feedback_controller.cpp:53:10: error: ‘cerr’ is not a member of ‘std’
   53 |     std::cerr << ss.str() << std::endl;
      |          ^~~~
/tmp/binarydeb/ros-rolling-linear-feedback-controller-4.0.3/src/linear_feedback_controller.cpp:2:1: note: ‘std::cerr’ is defined in header ‘<iostream>’; this is probably fixable by adding ‘#include <iostream>’
    1 | #include "linear_feedback_controller/linear_feedback_controller.hpp"
  +++ |+#include <iostream>
    2 |
```